# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - Arm1_controller
    - Arm2_controller

  Arm1_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - J1_1
      - J1_2
      - J1_3
      - J1_4
      - J1_5
      - J1_6
  Arm2_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - J2_1
      - J2_2
      - J2_3
      - J2_4
      - J2_5
      - J2_6
